name: tekartik_firebase_vertex_ai_google
description: Standalone vertex ai mapped to google generative ai
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  google_generative_ai: ">=0.4.6"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  tekartik_firebase_vertex_ai:
    git:
      url: https://github.com/tekartik/firebase_vertex_ai.dart
      path: vertex_ai
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart

dev_dependencies:
  lints: ">=5.0.0"
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      path: packages/prj_tktools
  test: ">=1.24.0"
resolution: workspace

