name: tekartik_firebase_vertex_ai_google
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  google_generative_ai: ">=0.4.6"
  dev_build: ">=1.1.0+1"
  process_run: ">=1.2.0+3"
  tekartik_firebase_vertex_ai:
    git:
      url: https://github.com/tekartik/firebase_vertex_ai.dart
      ref: dart3a
      path: vertex_ai

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
