name: tekartik_firebase_vertex_ai
description: Vertex AI abstraction
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  # path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
